# Generated by Django 2.2.5 on 2019-12-26 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0002_auto_20191226_1838'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='entry',
            unique_together={('date', 'product', 'branch')},
        ),
    ]
